services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: quiz_user
      POSTGRES_PASSWORD: quiz_password
      POSTGRES_DB: quiz_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: sh -c "sleep 3 && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://quiz_user:quiz_password@db:5432/quiz_db

  frontend_widget:
    build: ./frontend_widget
    ports:
      - "5173:5173"
    volumes:
      - ./frontend_widget:/app
      - /app/node_modules
    depends_on:
      - backend

  frontend_admin:
    build: ./frontend_admin
    ports:
      - "5174:5174"
    volumes:
      - ./frontend_admin:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data: